import NextTopLoader from 'nextjs-toploader'
import type { Metadata } from 'next'
import './globals.css'
import Providers from '@/providers'
import Header from '@/components/shared/Header'
import { cerapro } from '@/lib/cerapro'

export const metadata: Metadata = {
  title: 'GreenShoop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode
  auth: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${cerapro.className} antialiased`}>
        <NextTopLoader color="#16A34A" />
        <Providers>
          <Header />
          <main>
            {children}
            {auth}
          </main>
        </Providers>
      </body>
    </html>
  )
}
